frase = ('Curso em Vídeo Python')
print(frase)
print(frase.upper(), frase.count('o'))
print(frase.title())
print(frase.capitalize())
print(frase.swapcase())
print(frase.replace('Python', 'Android'),(frase.find('Android')))
print(frase.split())
dividido = frase.split()
print(dividido[0:3])